In [2]:
import numpy as np
l = [1, 2, 3, 4, 5, 6]
arr = np.array(l, dtype=int)
print(arr)

[1 2 3 4 5 6]


In [3]:
arr2 = arr.reshape(3, 2)
print(arr2)
print(arr2.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [4]:
arr3 = np.array(l, dtype=float).reshape(3, 2)
print(arr3)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [5]:
x = np.matrix([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)
y = np.matrix([1, 2, 3, 4, 5, 6]).reshape(3, 2)
print(x*y)

[[ 22  28]
 [ 49  64]
 [ 76 100]]


In [6]:
np.sum(x)

45